[package]
name = "ethereum_rust-l2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
ethereum-types.workspace = true
ethereum_rust-rpc.workspace = true
ethereum_rust-storage.workspace = true
# TODO We need the patch_000_mdbx branch, check how to reference the repo directly (merge the branch?).
# Using this branch to have De/Serialization for the Block type.
# ethereum_rust
ethereum_rust-core = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-core", branch = "patch_000_mdbx", default-features = false, features = [
    "no_libmdbx",
] }
hex.workspace = true
bytes.workspace = true
jsonwebtoken.workspace = true
sp1-sdk = "2.0.0"

prover-lib = { path = "./prover/sp1/lib" }

[lib]
path = "./l2.rs"
