[package]
name = "ethrex-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethrex-rlp.workspace = true
ethrex-common.workspace = true
ethrex-trie.workspace = true

ethereum-types.workspace = true
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
sha3.workspace = true
hex.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
libmdbx = { workspace = true, optional = true }
redb = { workspace = true, optional = true }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", package = "reth-codecs" , tag = "v1.1.0"}
reth-codecs-derive = { git = "https://github.com/paradigmxyz/reth", package = "reth-codecs-derive" , tag = "v1.1.0"}
reth-db-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-db-api" , tag = "v1.1.0"}
reth-db-common = { git = "https://github.com/paradigmxyz/reth", package = "reth-db-common" , tag = "v1.1.0"}
reth-db-models = { git = "https://github.com/paradigmxyz/reth", package = "reth-db-models" , tag = "v1.1.0"}
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db" , tag = "v1.1.0"}
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", package = "reth-storage-errors" , tag = "v1.1.0"}
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", package = "reth-libmdbx" , tag = "v1.1.0"}
reth-mdbx-sys = { git = "https://github.com/paradigmxyz/reth", package = "reth-mdbx-sys" , tag = "v1.1.0"}
reth-nippy-jar = { git = "https://github.com/paradigmxyz/reth", package = "reth-nippy-jar" , tag = "v1.1.0"}
reth-provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider" , tag = "v1.1.0"}
reth-storage-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-storage-api" , tag = "v1.1.0"}
alloy-consensus = "0.4.2"
alloy-primitives = "0.8.25"

[features]
default = []
libmdbx = ["dep:libmdbx", "ethrex-trie/libmdbx"]
redb = ["dep:redb"]

[dev-dependencies]
hex.workspace = true
hex-literal.workspace = true
tempdir = "0.3.7"

[lib]
path = "./lib.rs"
