global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "ethrex L1"
    static_configs:
      - targets: ["localhost:3701"]
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: "lighthouse consensus"
    static_configs:
      - targets: ["localhost:5054"]
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: "ethereum-metrics-exporter"
    static_configs:
      - targets: ["localhost:9093"]
    scrape_interval:  5s
    metrics_path: /metrics
