[package]
name = "zkvm_interface"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_with = "3.11.0"
serde_json = "1.0.117"
thiserror = "2.0.9"
kzg-rs = { version = "0.2.6", optional = true }
c-kzg = { version = "2.1.1", optional = true }

ethrex-common = { path = "../../../../common/", default-features = false }
ethrex-blockchain = { path = "../../../../blockchain/", default-features = false }
ethrex-vm = { path = "../../../../vm", default-features = false }
ethrex-rlp = { path = "../../../../common/rlp", default-features = false }
ethrex-storage = { path = "../../../../storage", default-features = false }
ethrex-trie = { path = "../../../../common/trie", default-features = false }
ethrex-l2-common = { path = "../../../common", default-features = false }

[build-dependencies]
risc0-build = { version = "2.1.2", optional = true }
sp1-build = { version = "5.0.0", optional = true }
sp1-sdk = { version = "5.0.0", optional = true }

[package.metadata.risc0]
methods = ["risc0"]

[features]
default = ["kzg-rs"]
risc0 = ["dep:risc0-build"]
sp1 = ["dep:sp1-build", "dep:sp1-sdk"]
l2 = ["ethrex-vm/l2"]
kzg-rs = ["dep:kzg-rs", "ethrex-vm/kzg-rs"]
c-kzg = ["dep:c-kzg", "ethrex-vm/c-kzg", "ethrex-common/c-kzg"]

[lib]
path = "./src/lib.rs"
