[package]
name = "ethrex-libmdbx"
description = "Idiomatic and safe MDBX wrapper (fork)"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
mdbx-sys.workspace = true

bitflags = { version = "2.9.1" }
byteorder = "1.5.0"
derive_more = { version = "2", default-features = false, features = ["full"] }
indexmap = "2.9.0"
parking_lot = "0.12"
smallvec = "1.15.0"
thiserror.workspace = true
tracing.workspace = true

dashmap = { version = "6.1.0", features = ["inline"], optional = true }

[features]
default = []
return-borrowed = []
read-tx-timeouts = ["dep:dashmap"]

[dev-dependencies]
criterion = { version = "0.6.0" }
rand.workspace = true
tempfile = "3.20.0"

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false
