[package]
name = "ethereum_rust-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_rust-rlp.workspace = true
ethereum_rust-core.workspace = true
ethereum_rust-storage.workspace = true
ethereum_rust-vm.workspace = true

thiserror.workspace = true
sha3.workspace = true
tracing.workspace = true
bytes.workspace = true

[lib]
path = "./blockchain.rs"

[features]
default = ["libmdbx"]
libmdbx = [
    "ethereum_rust-core/libmdbx",
    "ethereum_rust-storage/libmdbx",
    "ethereum_rust-vm/libmdbx",
]
