- name: Database Setup
  hosts: database
  become: true
  vars:
    postgresql_version: 17

  tasks:
    - name: Add PostgreSQL GPG key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        keyring: /etc/apt/trusted.gpg.d/postgresql.gpg
        state: present

    - name: Add PostgreSQL repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"
        state: present
        filename: pgdg

    - name: "Install PostgreSQL {{ postgresql_version }}"
      apt:
        name: "postgresql-{{ postgresql_version }}"
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running
      systemd:
        name: postgresql
        state: started
        enabled: true
