- name: Ethrex L1 Setup
  hosts: ethrex_l1
  vars:
    ethrex_dir: "/home/{{ ansible_user }}/ethrex"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Clang and related tools
      apt:
        name:
          - libclang-dev
          - clang
          - tmux
          - rsync
          - linux-perf
          - git
          - pkg-config
        state: present

    - name: Check if rustup is installed
      stat:
        path: /home/{{ ansible_user }}/.cargo/bin/rustc
      register: rustup_check

    - name: Install rustup
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      when: not rustup_check.stat.exists

    - name: Add Rust to PATH
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: source $HOME/.cargo/env
        create: yes
      when: not rustup_check.stat.exists

    - name: Clone Ethrex repository
      git:
        repo: "https://github.com/lambdaclass/ethrex.git"
        dest: "{{ ethrex_dir }}"
        version: main

    - name: Get architecture
      set_fact:
        architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"

    - name: Download Ethereum Metrics Exporter
      get_url:
        url: "https://github.com/ethpandaops/ethereum-metrics-exporter/releases/download/v{{ ethereum_metrics_exporter_version }}/ethereum-metrics-exporter_{{ ethereum_metrics_exporter_version }}.linux_{{ architecture }}.tar.gz "
        dest: "/tmp/ethereum_metrics_exporter_{{ ethereum_metrics_exporter_version }}.tar.gz"
        mode: '0644'

    - name: Extract Ethereum Metrics Exporter
      unarchive:
        src: "/tmp/ethereum_metrics_exporter_{{ ethereum_metrics_exporter_version }}.tar.gz"
        dest: /tmp/
        remote_src: yes
      
    - name: Move Ethereum Metrics Exporter
      copy:
        remote_src: true
        src: "/tmp/ethereum_metrics_exporter_{{ ethereum_metrics_exporter_version }}_linux_{{ architecture }}"
        dest: "/usr/local/bin/ethereum_metrics_exporter"
        mode: '0755'

    - name: Ensure user systemd directory exists
      file:
        path: "/home/{{ ansible_user }}/.config/systemd/user"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    - name: Install Ethrex L1
      template:
        src: services/ethrex-l1.service.j2
        dest: /home/{{ ansible_user }}/.config/systemd/user/ethrex-l1.service
      vars:
        # envvars to pass to the L1 template systemd service
    
    - name: Start Lighthouse
    
    - name: Start Ethrex L1
