name: Add PR to Project

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        if: contains(github.event.pull_request.title, 'l1') || contains(github.event.pull_request.title, 'levm') || contains(github.event.pull_request.title, 'core')
        with:
          project-url: https://github.com/orgs/lambdaclass/projects/31 # ethrex_l1 project number
          github-token: ${{ secrets.GH_PROJECT_PERSONAL_ACCESS_TOKEN }}
