name: Add to Project

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/add-to-project@1.0.2
        with:
          project-url: https://github.com/orgs/lambdaclass/projects/31 # ethrex_l1 number
          github-token: ${{ secrets.GITHUB_TOKEN }}
