name: trie benchmark

on:
  workflow_call:
  pull_request:
    branches: ["**"]
    paths:
      - "crates/common/trie/**"

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build-ethrex-trie:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        trie-version: ["head", "cita"]
    steps:
      - name: Populate cache
        uses: actions/cache@v4
        id: cache
        with:
          path: crates/common/trie
          key: trie-${{ github.event.pull_request[matrix.trie-version].sha }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ matrix.trie-version == 'cita' || matrix.trie-version == 'head' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request[matrix.branch].sha }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ matrix.trie-version == 'base' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request[matrix.trie-version].sha }}

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: dtolnay/rust-toolchain@stable

      - name: Build ethrex trie benchmark
        if: ${{ matrix.trie-version != 'cita' }}
        run: |
          set -x
          cd crates/common/trie
          ls -lah
          cargo bench --bench ethrex_trie_bench -- --output-format bencher | tee bench-${{ matrix.trie-version }}.txt

      - name: Build cita trie benchmark
        if: ${{ matrix.trie-version == 'cita' }}
        run: |
          cd crates/common/trie
          make build-cita-bench
          cargo bench --bench cita_trie_bench -- --output-format bencher | tee bench-${{ matrix.trie-version }}.txt
          ls -lah
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          name: Trie Benchmark
          output-file-path: crates/common/trie/bench-${{ matrix.trie-version}}.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          summary-always: true
          auto-push: true
