name: trie benchmark

on:
  workflow_call:
  pull_request:
    branches: ["**"]
    paths:
      - "crates/common/trie/**"

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build-ethrex-trie:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        trie-version: ["head", "base"]
    steps:
      - name: Populate cache
        uses: actions/cache@v4
        id: cache
        with:
          path: crates/common/trie
          key: trie-${{ github.event.pull_request[matrix.trie-version].sha }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ matrix.trie-version == 'cita' || matrix.trie-version == 'head' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request[matrix.branch].sha }}

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ matrix.trie-version == 'base' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request[matrix.trie-version].sha }}

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: dtolnay/rust-toolchain@stable

      - name: Benchmarks
        uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "crates/common/trie"
          benchName: "trie_bench"
          token: ${{ secrets.GITHUB_TOKEN }}
