name: Run Cancun Invalid NewPayload Hive Tests

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  run-cancun-invalid-newpayload:
    name: Cancun Invalid NewPayload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Hive
        run: make setup-hive

      - name: Pull ethrex image
        run: |
          docker pull ghcr.io/lambdaclass/ethrex:latest
          docker tag ghcr.io/lambdaclass/ethrex:latest ethrex:latest

      - name: Run Hive Simulation
        run: |
          cd hive
          ./hive \
            --client-file ../fixtures/network/hive_clients/ethrex.yml \
            --client ethrex \
            --sim ethereum/engine \
            --sim.limit "cancun/Invalid NewPayload"
