name: Block Import Benchmark

on:
  workflow_call:
  push:
    branches: [main]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Extract Rust version from rust-toolchain.toml
        id: rustver
        run: |
          rust_version=$(grep -E '^[[:space:]]*channel[[:space:]]*=' rust-toolchain.toml \
                   | sed -E 's/.*"([^"]+)".*/\1/')
          echo "rust_version=${rust_version}" >>"$GITHUB_OUTPUT"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rustver.outputs.rust_version }}

      - name: Update package lists
        run: sudo apt-get update

      - name: Install gnuplot
        run: sudo apt-get install -y gnuplot

      - name: Run benchmark
        run: cd cmd/ethrex && cargo bench --bench import_blocks_benchmark -- --output-format bencher |sed 2d | tee output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: cmd/ethrex/output.txt
          benchmark-data-dir-path: "benchmarks"
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          alert-threshold: "130%"
          comment-on-alert: true
