# TODO: uncomment "if: ${{ always() && github.event_name == 'merge_group' }}" lines when reenabling this workflow in the merge queue
name: L2 (SP1 Backend)
on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CI_ETHREX_WORKDIR: /usr/local/bin
  PROVER: sp1

jobs:
  test:
    name: Integration Test Prover SP1
    runs-on: gpu
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@1.87.0

      - name: Set up Rust cache
        # if: ${{ always() && github.event_name == 'merge_group' }}
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: RISC-V SP1 toolchain install
        # if: ${{ always() && github.event_name == 'merge_group' }}
        run: |
          . "$HOME/.cargo/env"
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up --version 5.0.0

      - name: Set up Docker Buildx
        # if: ${{ always() && github.event_name == 'merge_group' }}
        uses: docker/setup-buildx-action@v3

      # This step is needed because of an state bug in the GPU runner.
      # Issue to fix this: https://github.com/lambdaclass/ethrex/pull/2741.
      - name: Clean .env
        # if: ${{ always() && github.event_name == 'merge_group' }}
        run: rm -rf crates/l2/.env

      - name: Build binaries
        # if: ${{ always() && github.event_name == 'merge_group' }}
        working-directory: crates/l2
        run: make build G=true

      - name: Run tests
        # if: ${{ always() && github.event_name == 'merge_group' }}
        working-directory: crates/l2
        run: make test

      - name: Destroy Docker containers and clean up
        if: always()
        working-directory: crates/l2
        run: |
          make down
          make clean

      - name: Ensure admin permissions in _work
        if: always()
        run: sudo chown admin:admin -R /home/admin/actions-runner/_work/
