# .github/workflows/set-pr-status.yml
name: Set PR Status to In Progress

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PROJECT_PERSONAL_ACCESS_TOKEN }}
          script: |
            // ========== FUNCTIONS ==========

            async function getProject(org, number) {
              const res = await github.graphql(`
                query($org: String!) {
                  organization(login: $org) {
                    projectsV2(first: 100) {
                      nodes {
                        id
                        title
                        number
                      }
                    }
                  }
                }
              `, { org });
              const project = res.organization.projectsV2.nodes.find(p => p.number === number);
              if (!project) throw new Error(`Project #${number} not found in org ${org}`);
              return project;
            }

            async function findProjectItem(projectId, prNumber) {
              let hasNextPage = true;
              let after = null;

              while (hasNextPage) {
                const res = await github.graphql(`
                  query($projectId: ID!, $after: String) {
                    node(id: $projectId) {
                      ... on ProjectV2 {
                        items(first: 100, after: $after) {
                          pageInfo {
                            hasNextPage
                            endCursor
                          }
                          nodes {
                            id
                            content {
                              ... on PullRequest {
                                number
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                `, { projectId, after });

                const items = res.node.items.nodes;
                const found = items.find(i => i.content?.number === prNumber);
                if (found) return found;

                hasNextPage = res.node.items.pageInfo.hasNextPage;
                after = res.node.items.pageInfo.endCursor;
              }

              return null;
            }

            async function getStatusFieldAndOption(projectId, fieldName, optionName) {
              const res = await github.graphql(`
                query($projectId: ID!) {
                  node(id: $projectId) {
                    ... on ProjectV2 {
                      fields(first: 100) {
                        nodes {
                          ... on ProjectV2SingleSelectField {
                            id
                            name
                            options {
                              id
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `, { projectId });

              const field = res.node.fields.nodes.find(f => f.name === fieldName);
              if (!field) throw new Error(`Field '${fieldName}' not found`);

              const option = field.options.find(opt => opt.name === optionName);
              if (!option) throw new Error(`Option '${optionName}' not found in field '${fieldName}'`);

              return { fieldId: field.id, optionId: option.id };
            }

            async function updateProjectItemField(projectId, itemId, fieldId, optionId) {
              await github.graphql(`
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(input: {
                    projectId: $projectId,
                    itemId: $itemId,
                    fieldId: $fieldId,
                    value: { singleSelectOptionId: $optionId }
                  }) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `, { projectId, itemId, fieldId, optionId });
            }


            // ========== MAIN LOGIC ==========
            const pr = context.payload.pull_request;
            const projectNumber = 31;
            const statusFieldName = "Status";
            const newStatus = "In Review";
            const orgLogin = "lambdaclass";


            const project = await getProject(orgLogin, projectNumber);
            const projectId = project.id;

            const item = await findProjectItem(projectId, pr.number);
            if (!item) {
              console.log(`PR #${pr.number} not found in project.`);
              return;
            }

            console.log(`PR #${pr.number} found in project with item ID: ${item.id}`);

            const { fieldId, optionId } = await getStatusFieldAndOption(projectId, statusFieldName, newStatus);
            await updateProjectItemField(projectId, item.id, fieldId, optionId);
