# .github/workflows/set-pr-status.yml
name: Set PR Status to In Progress

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PROJECT_PERSONAL_ACCESS_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const projectNumber = 31;
            const statusFieldName = "Status";
            const newStatus = "In Review";
            const orgLogin = "lambdaclass";

            // Fetch first 100 projects in the organization
            const projects = await github.graphql(`
              query($org: String!) {
                organization(login: $org) {
                  projectsV2(first: 100) {
                    nodes {
                      id
                      title
                      number
                    }
                  }
                }
              }
            `, { org: orgLogin });

            const project = projects.organization.projectsV2.nodes.find(p => p.number === projectNumber);
            if (!project) {
              throw new Error(`Project #${projectNumber} not found in org ${orgLogin}`);
            }
            const projectId = project.id;


            // Fetch all items of the project, in batches of 100 elements.
            let hasNextPage = true;
            let after = null;

            while (hasNextPage) {
              const result = await github.graphql(`
                query($projectId: ID!, $after: String) {
                  node(id: $projectId) {
                    ... on ProjectV2 {
                      items(first: 100, after: $after) {
                        pageInfo {
                          hasNextPage
                          endCursor
                        }
                        nodes {
                          id
                          content {
                            ... on PullRequest {
                              id
                              number
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `, {
                projectId,
                after
              });

              const items = result.node.items.nodes;
              const foundItem = items.find(i => i.content?.number === pr.number);
              if (foundItem) {
                item = foundItem;
                break;
              }

              hasNextPage = result.node.items.pageInfo.hasNextPage;
              after = result.node.items.pageInfo.endCursor;
            }


            let itemId;
            if (item) {
              console.log(`PR #${pr.number} found in project with item ID: ${item.id}`);
              itemId = item.id;
            } else {
              console.log(`PR #${pr.number} not found in project.`);
            }

            // Validate that project has the correct field and options and get them.
            const fieldsResult = await github.graphql(`
              query($projectId: ID!) {
                node(id: $projectId) {
                  ... on ProjectV2 {
                    fields(first: 100) {
                      nodes {
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, { projectId });

            const statusField = fieldsResult.node.fields.nodes.find(f => f.name === statusFieldName);
            if (!statusField) {
              throw new Error(`Field '${statusFieldName}' not found`);
            }

            const option = statusField.options.find(opt => opt.name === newStatus);
            if (!option) {
              throw new Error(`Option '${newStatus}' not found in field '${statusFieldName}'`);
            }

            // Update the Status field
            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId,
              fieldId: statusField.id,
              optionId: option.id
            });
