name: Benchmark LEVM vs REVM

on:
  pull_request:
    branches: ["**"]
    paths:
      - "crates/vm/levm/**"
      - ".github/workflows/pr_perf_levm.yaml"

permissions:
  pull-requests: write

jobs:
  benchmark-pr:
    name: Benchmark for PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.87.0
        with:
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build main benchmark
        run: |
          cd crates/vm/levm
          make build-revm-comparison
      - name: Upload main benchmark binary
        uses: actions/upload-artifact@v4
        with:
          name: pr-result
          path: crates/vm/levm/target/release/benchmark

  benchmark-main:
    name: Benchmark for Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.87.0
        with:
          components: rustfmt, clippy

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Build main benchmark
        run: |
          cd crates/vm/levm
          make build-revm-comparison
      - name: Upload main benchmark binary
        uses: actions/upload-artifact@v4
        with:
          name: main-result
          path: crates/vm/levm/target/release/benchmark

  combine-results:
    name: Combine Benchmark Results
    runs-on: ubuntu-latest
    needs: [benchmark-pr, benchmark-main]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine@1.19

      - name: Install solc
        uses: pontem-network/get-solc@master
        with:
          version: v0.8.29

      - name: Download PR results
        uses: actions/download-artifact@v4
        with:
          name: pr-result
          path: ./pr

      - name: Download main results
        uses: actions/download-artifact@v4
        with:
          name: main-result
          path: ./main

      - name: Run benchmarks
        run: |
          chmod +x ./main/benchmark
          chmod +x ./pr/benchmark
          cd crates/vm/levm
          make revm-comparison-ci
          for f in Factorial.md FactorialRecursive.md Fibonacci.md ManyHashes.md BubbleSort.md ERC20Transfer.md ERC20Mint.md ERC20Approval.md; do
            awk -F'|' -v file="${f%.md}" '      
            /`main_revm_/ {
              main_revm_row = $0;
              gsub(/±.*/, "", $3); # Remove ± part from $3 posicion of the row
              gsub(/[[:space:]]/, "", $3); # Remove spaces
              main_revm = $3 + 0; # Convert to number
            }
            /`main_levm_/ {
              main_levm_row = $0;
              gsub(/±.*/, "", $3);
              gsub(/[[:space:]]/, "", $3);
              main_levm = $3 + 0;
            }
            /`pr_revm_/ {
              pr_revm_row = $0;
              gsub(/±.*/, "", $3);
              gsub(/[[:space:]]/, "", $3);
              pr_revm = $3 + 0;
            }
            /`pr_levm_/ {
              pr_levm_row = $0;
              gsub(/±.*/, "", $3);
              gsub(/[[:space:]]/, "", $3);
              pr_levm = $3 + 0;
            }
            END {
              if (main_revm && main_levm && pr_revm && pr_levm) {
                revm_delta = ((main_revm > pr_revm) ? main_revm - pr_revm : pr_revm - main_revm)/(main_revm + pr_revm);
                levm_delta = ((main_levm > pr_levm) ? main_levm - pr_levm: pr_levm - main_levm)/(main_levm + pr_levm);
                error_margin = 0.1;
                if ((revm_delta > error_margin) || (levm_delta > error_margin)) {
                  printf "#### Benchmark Results: %s \n", file
                  print "| Command | Mean [s] | Min [s] | Max [s] | Relative |"
                  print "|:---|---:|---:|---:|---:|"
                  print main_revm_row
                  print main_levm_row
                  if (revm_delta > error_margin) {
                      print pr_revm_row
                  }
                  if (levm_delta > error_margin) {
                      print pr_levm_row
                  }
                }
              } else {
                printf "#### Benchmark Results: %s \n", file
                print "No results."
              }
            }
            ' "$f" >> ../../../result.md
          done

          if [ ! -s ../../../result.md ]; then
            echo "No significant difference was registered for any benchmark run." > ../../../result.md
          fi

      - name: Find comment
        continue-on-error: true
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Benchmark Results Comparison"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: result.md
          edit-mode: replace
