name: Benchmark Block building

on:
  pull_request:
    branches: ["**"]

permissions:
  pull-requests: write

jobs:
  build-block-benchmark:
    if: contains(github.event.pull_request.labels.*.name, 'performance')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Extract Rust version from rust-toolchain.toml
        id: rustver
        run: |
          rust_version=$(grep -E '^[[:space:]]*channel[[:space:]]*=' rust-toolchain.toml \
                   | sed -E 's/.*"([^"]+)".*/\1/')
          echo "rust_version=${rust_version}" >>"$GITHUB_OUTPUT"
          echo "Rust version: ${rust_version}"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rustver.outputs.rust_version }}

      - name: Benchmarks
        uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "cmd/ethrex/bench"
          benchName: "build_block_benchmark"
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
